### ISSUE TITLE
Intervals stop working after request error

### ISSUE THREAD

**Issue by stoically** [FlixCoder/matrix-bot#22]
When a request fails like so

> 2022-10-09T04:06:37.466893Z ERROR matrix_run: matrix_bot: error=error sending request 

There are no more interval DEBUG messages about intervals anymore. So it seems a failing request crashes the interval task.

**Comment by FlixCoder** [comment]
Looks like the matrix SDK has a bug or so? It is part of matrix_run with the continuous sync, if the sync stops the bot should shut down. Or if it was an earlier version it might be fixed now?

**Comment by stoically** [comment]
I'm on the latest version and it still happens. Let me know if I can provide more debug info.

Maybe an additional detail: After the request error no more intervals are run, also not the RSS interval.

**Comment by stoically** [comment]
Might also be worth to retry a few times for sending http requests.

**Comment by FlixCoder** [comment]
It is a matrix request that fails I think ^^

**Comment by FlixCoder** [comment]
https://github.com/FlixCoder/matrix-bot/pull/26 Should make it properly shutdown now, so that it can restart automatically. Maybe I should consider restarting the matrix sync on error, seems to happen more often than I thought..

**Comment by stoically** [comment]
I wouldn't consider this solved. Properly shutting down still means it gets stuck in an endless crashloop.

**Comment by FlixCoder** [comment]
Well it retries requests, it only stops when there is no access to the matrix server after a few retries. At least I think so. I would consider that sensible, but feel free to re-open, especially when it isn't as expected. Would possibly be some different issue though

**Comment by stoically** [comment]
Non-collaborator issue authors can't reopen issues if they didn't close it themselves.

Maybe I misunderstood the solution for this issue. Will try and report back if it isn't fixed. Thanks.
