### ISSUE TITLE
error decoding response body: missing field `user`

### ISSUE THREAD

**Issue by stoically** [FlixCoder/matrix-bot#24]
This popped up in the logs:

> 2022-10-10T14:41:23.484143Z ERROR matrix_bot::intervals: Error in intervals: error decoding response body: missing field `user` at line 1 column 16284

It also didn't post any other notifications. So it seems that an error in one notification prevents from more notifs to be processed?

**Comment by FlixCoder** [comment]
Yeah it stops all notifs, but should retry them all next time  (but will fail again with the same error) ^^ should be an easy fix, thanks

**Comment by stoically** [comment]
It also seems to repost old notifications if posting one notif has an error.
